version: '3'

services:
  discovery:
    build: 
      context: ./Eureka-Server
      dockerfile: dockerfile
    ports:
      - 8761:8761
    image: "eureka-service"
      
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8006:8006
    depends_on:
      - discovery
    networks:
      - app-network

  auth:
    build:
      context: ./auth-django
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    depends_on:
      - auth-db
      - discovery
    networks:
      - app-network

  forum:
    build:
      context: ./forum-service
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - forum-db
      - discovery
    networks:
      - app-network

  chat:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - chat-db
      - discovery
    networks:
      - app-network

  task:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - 8004:8004
    depends_on:
      - task-db
      - discovery
    networks:
      - app-network

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth-service
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    command: ["-c", "config_file=/usr/pgsql-14/bin/postgresql.conf"]

  forum-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: forum-service
    volumes:
      - forum_postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    command: ["-c", "config_file=/usr/pgsql-14/bin/postgresql.conf"]

  chat-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat-service
    volumes:
      - chat_postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    command: ["-c", "config_file=/usr/pgsql-14/bin/postgresql.conf"]

  task-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task-service
    volumes:
      - task_postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    command: ["-c", "config_file=/usr/pgsql-14/bin/postgresql.conf"]

volumes:
  auth_postgres_data:
  forum_postgres_data:
  chat_postgres_data:
  task_postgres_data:

networks:
  app-network:
